
# Syntax highlighting
markdown: Kramdown
highlighter: rouge

# Permalinks
permalink:           /:title

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              your locale language # eg. en_us
name:				         Arnu Pretorius - blog
title:               Arnu Pretorius - blog
tagline:             'tagline'
description:         'Thoughts on learning'
url:                 https://arnupretorius.github.io
rss:                 rss feed url
baseurl:             'https://arnupretorius.github.io/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
# disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Arnu Pretorius
  url:            	 your site url
#  facebook:          username
  twitter:           arnupretorius
#  google_plus:       username
  linkedin:          arnupretorius
#  dribbble:          username
#  pinterest:         username
#  kiva:              username

# fb_admins:           your facebook profile id
# fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
